[package]
name = "solo-pc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
chacha20 = { version = "0.7", features = ["rng"] }
delog = "0.1.0"
embedded-hal = { version = "0.2", features = ["unproven"] }
generic-array = "0.14.3"
interchange.workspace = true
nb.workspace = true

admin-app.workspace = true
apdu-dispatch.workspace = true
ctap-types.workspace = true
ctaphid-dispatch.workspace = true
fido-authenticator = { workspace = true, optional = true }
piv-authenticator.workspace = true
trussed.workspace = true
trussed-core.workspace = true

# components
usbd-ccid.workspace = true
usbd-ctaphid.workspace = true
nfc-device.workspace = true
ndef-app.workspace = true

# storage
littlefs2.workspace = true

[features]
default = []

# Use to auto-succeed every user presence check
no-buttons = []

# Reconfigure the NFC chip in any case
reconfigure-nfc = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []
