[package]
name = "provisioner-app"
version = "0.1.0"
authors = ["Conor Patrick <conor@solokeys.com>"]
edition = "2024"

[dependencies]
apdu-dispatch = "0.3"
defmt = "1.0.1"
heapless = "0.8"
lpc55-hal = { version = "0.3", features = ["rtic-peripherals"] }
littlefs2 = "0.6"
trussed = "0.1"
p256 = { version = "0.9", default-features = false, features = ["arithmetic"] }
salty = "0.3"

[features]
test-attestation = []
