[package]
name = "nfc-device"
version = "0.0.1"
authors.workspace = true
edition = "2024"

[dependencies]
defmt         .workspace = true
embedded-time .workspace = true
heapless      .workspace = true
nb            .workspace = true
apdu-dispatch .workspace = true
iso7816       .workspace = true
interchange   .workspace = true
